export const bizz_service_desc = 'Abhaya Libre bizz'
export const air_service_desc = 'Abhaya Libre air'
export const wedding_service_desc = 'Abhaya Libre wed'
export const bus_sevice_desc = 'Abhaya Libre bus'
export const prom_service_desc = 'Abhaya Libre prom'
export const party_service_desc = 'Abhaya Libre party'
export const hourly_sevice_desc = 'Abhaya Libre hourly'
export const casino_sevice_desc = 'Abhaya Libre cas'